name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v5.9.0
          target: iOS
